---
language: ruby
bundler_args: --without system_tests
script: "bundle install && rake spec_prep && rspec"
matrix:
  fast_finish: true
  include:
  - rvm: 2.0.0
    env: PUPPET_GEM_VERSION="~> 3.0"
  - rvm: 2.0.0
    env: PUPPET_GEM_VERSION="~> 3.5" 
  - rvm: 2.0.0
    env: PUPPET_GEM_VERSION="~> 3.8" 
  - rvm: 2.0.0
    env: PUPPET_GEM_VERSION="~> 4.0" 
notifications:
  email: true
